
global:
  scrape_interval:     15s #


  external_labels:
    monitor: 'prometheus_watch'


scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'backend'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:3030/metrics']